import { useState } from 'react';
import { useSeoMeta } from '@unhead/react';
import { Capacitor } from '@capacitor/core';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { useToast } from '@/hooks/useToast';
import {
  impactLight,
  impactMedium,
  impactHeavy,
  notificationSuccess,
  notificationWarning,
  notificationError,
  selectionChanged,
} from '@/lib/haptics';
import { downloadTextFile, openUrl } from '@/lib/downloadFile';
import { useSecureLocalStorage } from '@/hooks/useSecureLocalStorage';

const platform = Capacitor.getPlatform(); // 'web' | 'ios' | 'android'
const isNative = Capacitor.isNativePlatform();

export default function Index() {
  useSeoMeta({
    title: 'Capacitor Example',
    description: 'A demo of Capacitor native features: haptics, secure storage, file download, deep links, and safe-area utilities.',
  });

  const { toast } = useToast();
  const [secretNote, setSecretNote, storageReady] = useSecureLocalStorage<string>('cap-example:note', '');
  const [noteInput, setNoteInput] = useState('');
  const [downloadCount, setDownloadCount] = useState(0);

  function handleSaveNote() {
    if (!noteInput.trim()) return;
    setSecretNote(noteInput.trim());
    setNoteInput('');
    notificationSuccess();
    toast({ title: 'Saved!', description: isNative ? 'Stored in Keychain / KeyStore.' : 'Stored in localStorage.' });
  }

  function handleClearNote() {
    setSecretNote('');
    impactLight();
    toast({ title: 'Cleared', description: 'Secret note removed.' });
  }

  async function handleDownload() {
    const count = downloadCount + 1;
    setDownloadCount(count);
    const content = `Capacitor Example Export #${count}\n\nPlatform: ${platform}\nTimestamp: ${new Date().toISOString()}\n\nThis file was generated by the Capacitor Example app.\n`;
    await downloadTextFile(`export-${count}.txt`, content);
    notificationSuccess();
    toast({ title: 'Downloaded!', description: isNative ? 'Saved to Documents folder.' : 'File download triggered.' });
  }

  async function handleOpenUrl() {
    impactLight();
    await openUrl('https://shakespeare.diy');
  }

  return (
    <div className="min-h-dvh-safe bg-background text-foreground">
      {/* Header — uses pt-safe so content clears the status bar on notch devices */}
      <header className="sticky top-0 z-10 bg-background/80 backdrop-blur border-b pt-safe">
        <div className="max-w-lg mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="text-2xl">⚡</span>
            <span className="font-bold text-lg tracking-tight">Capacitor Example</span>
          </div>
          <Badge variant={isNative ? 'default' : 'secondary'} className="capitalize">
            {platform}
          </Badge>
        </div>
      </header>

      <main className="max-w-lg mx-auto px-4 py-6 pb-safe-or-8 space-y-6">

        {/* Platform info */}
        <Card className="border-dashed">
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              🌐 Platform Detection
            </CardTitle>
            <CardDescription>
              Capacitor detects whether the app is running natively or on the web.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Platform</span>
              <span className="font-mono font-medium capitalize">{platform}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Native?</span>
              <span className="font-mono font-medium">{isNative ? 'Yes' : 'No (web)'}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Storage backend</span>
              <span className="font-mono font-medium text-xs">{isNative ? 'Keychain / KeyStore' : 'localStorage'}</span>
            </div>
          </CardContent>
        </Card>

        {/* Haptics */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              📳 Haptic Feedback
            </CardTitle>
            <CardDescription>
              On iOS/Android this uses the Taptic Engine. On web it falls back to{' '}
              <code className="font-mono text-xs">navigator.vibrate()</code> (Android browsers only).
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <div>
              <p className="text-xs text-muted-foreground mb-2 font-medium uppercase tracking-wide">Impact</p>
              <div className="flex flex-wrap gap-2">
                <Button size="sm" variant="outline" onClick={impactLight}>Light</Button>
                <Button size="sm" variant="outline" onClick={impactMedium}>Medium</Button>
                <Button size="sm" variant="outline" onClick={impactHeavy}>Heavy</Button>
                <Button size="sm" variant="outline" onClick={selectionChanged}>Selection</Button>
              </div>
            </div>
            <Separator />
            <div>
              <p className="text-xs text-muted-foreground mb-2 font-medium uppercase tracking-wide">Notification</p>
              <div className="flex flex-wrap gap-2">
                <Button size="sm" variant="outline" className="text-green-600 border-green-200 hover:bg-green-50 dark:border-green-800 dark:hover:bg-green-950" onClick={notificationSuccess}>
                  ✅ Success
                </Button>
                <Button size="sm" variant="outline" className="text-yellow-600 border-yellow-200 hover:bg-yellow-50 dark:border-yellow-800 dark:hover:bg-yellow-950" onClick={notificationWarning}>
                  ⚠️ Warning
                </Button>
                <Button size="sm" variant="outline" className="text-red-600 border-red-200 hover:bg-red-50 dark:border-red-800 dark:hover:bg-red-950" onClick={notificationError}>
                  ❌ Error
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Secure Storage */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              🔐 Secure Storage
            </CardTitle>
            <CardDescription>
              On native, data is stored in iOS Keychain / Android KeyStore — never in plaintext.
              On web it uses <code className="font-mono text-xs">localStorage</code>.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {!storageReady ? (
              <div className="h-8 bg-muted rounded animate-pulse" />
            ) : secretNote ? (
              <div className="rounded-lg bg-muted px-3 py-2 text-sm flex items-start justify-between gap-2">
                <div>
                  <p className="text-xs text-muted-foreground mb-0.5">Stored secret note:</p>
                  <p className="font-medium">{secretNote}</p>
                </div>
                <Button size="sm" variant="ghost" className="shrink-0 text-destructive hover:text-destructive" onClick={handleClearNote}>
                  Clear
                </Button>
              </div>
            ) : (
              <p className="text-sm text-muted-foreground italic">No note stored yet.</p>
            )}
            <div className="flex gap-2">
              <div className="flex-1 space-y-1">
                <Label htmlFor="note-input" className="text-xs">Secret note</Label>
                <Input
                  id="note-input"
                  placeholder="Type something secret…"
                  value={noteInput}
                  onChange={(e) => setNoteInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleSaveNote()}
                />
              </div>
              <Button className="self-end" onClick={handleSaveNote} disabled={!noteInput.trim()}>
                Save
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* File Download */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              📁 File Download
            </CardTitle>
            <CardDescription>
              On native, the file is written to the app's Documents folder (visible in iOS Files /
              Android). On web, a browser download is triggered.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button onClick={handleDownload} className="w-full">
              Download export-{downloadCount + 1}.txt
            </Button>
          </CardContent>
        </Card>

        {/* Open URL / Share Sheet */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              🔗 Open URL / Share Sheet
            </CardTitle>
            <CardDescription>
              On native, this opens the OS share sheet (WKWebView blocks{' '}
              <code className="font-mono text-xs">window.open</code>). On web, it opens a new tab.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Button variant="outline" onClick={handleOpenUrl} className="w-full">
              Open shakespeare.diy
            </Button>
          </CardContent>
        </Card>

        {/* Safe Area */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              📐 Safe-Area Utilities
            </CardTitle>
            <CardDescription>
              This page uses <code className="font-mono text-xs">pt-safe</code> on the header and{' '}
              <code className="font-mono text-xs">pb-safe-or-8</code> on the main content so nothing
              is clipped behind the notch or home indicator on iOS/Android.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            <div className="rounded-md bg-muted p-3 font-mono text-xs space-y-1">
              <p><span className="text-blue-500">header</span> → <span className="text-green-500">pt-safe</span></p>
              <p><span className="text-blue-500">main</span> → <span className="text-green-500">pb-safe-or-8</span></p>
              <p><span className="text-blue-500">min-height</span> → <span className="text-green-500">min-h-dvh-safe</span></p>
            </div>
            <p className="text-xs text-muted-foreground">
              Requires <code className="font-mono">viewport-fit=cover</code> in{' '}
              <code className="font-mono">index.html</code> — already set in this project.
            </p>
          </CardContent>
        </Card>

        {/* Deep Links */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              🔀 Deep Links
            </CardTitle>
            <CardDescription>
              The <code className="font-mono text-xs">&lt;DeepLinkHandler /&gt;</code> component is
              already wired into <code className="font-mono text-xs">AppRouter.tsx</code>. It forwards
              OS-level URL opens into React Router.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-2 text-sm">
            <div className="rounded-md bg-muted p-3 font-mono text-xs space-y-1">
              <p><span className="text-yellow-500">iOS scheme</span> → CapacitorExample://</p>
              <p><span className="text-green-500">Android scheme</span> → https://</p>
            </div>
            <p className="text-xs text-muted-foreground">
              Universal Links (iOS) and App Links (Android) require hosting verification files on
              your domain. Custom schemes work out-of-the-box after <code className="font-mono">npx cap sync</code>.
            </p>
          </CardContent>
        </Card>

        {/* Native Bootstrap */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-base flex items-center gap-2">
              🚀 Native Bootstrap
            </CardTitle>
            <CardDescription>
              <code className="font-mono text-xs">bootstrapNative()</code> runs before React mounts.
              It hides the iOS keyboard accessory bar and keeps system bar icons in sync with the
              app's light/dark theme.
            </CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            Already called in <code className="font-mono text-xs">src/main.tsx</code> — nothing extra to do.
          </CardContent>
        </Card>

        {/* Footer */}
        <p className="text-center text-xs text-muted-foreground pt-2">
          Vibed with{' '}
          <a
            href="https://shakespeare.diy"
            className="underline underline-offset-2 hover:text-foreground transition-colors"
            onClick={(e) => { e.preventDefault(); openUrl('https://shakespeare.diy'); }}
          >
            Shakespeare
          </a>
        </p>

      </main>
    </div>
  );
}
